### ISSUE TITLE
How to show decimal values precision on phoria canvas

### ISSUE THREAD

**Issue by stoskoverflowcomunity** [kevinroast/phoria.js#22]
How I can show high precision values on phoria canvas

Etc.
points.push({x:52.68409940200493,y:0,z:8.370766639709473},{x:52.78118340200493,y:0,z:8.372654914855957},{x:52.99908340200493,y:0,z:8.373513221740723});

Is there any way to do that?

**Comment by kevinroast** [comment]
JavaScript stores numbers as 64bit floating point that is as high precision as you are going to get. Internally the library maintains those values, but when you display them perhaps there is loss in rounding?
