### ISSUE TITLE
Shadow

### ISSUE THREAD

**Issue by contributeur** [kevinroast/phoria.js#26]
hi ! 

Congrulation for your amazing project ! 

Will it be possible in a future version of shading manage ?
Currently if a cube hides another cube relative to a spot hidden then the cube is illuminated as if the other cube does not exist ....

**Comment by kevinroast** [comment]
I suspect not :( because it is all software rendered it would of course be possible but very, very slow I expect. For advanced shading you are better off using a WebGL library.
