### ISSUE TITLE
Plans for type definitions (TypeScript)?

### ISSUE THREAD

**Issue by khalla** [kevinroast/phoria.js#28]
Hi Kevin, great project, the only one so far compatible with IE, so, congratulations.

Any plans for Type Definitions for typescript?

I'm developing an angular/typecript app and those definitions would be nice to have.

I'm going to fork your project and then start designing them, maybe later you consider that as a contribution.

Cheers,
Renato

**Comment by kevinroast** [comment]
Hi, thanks for your comments. I don't have any plans for those, but would be happy to take the type des as a contribution.
Cheers,

Kev
