### ISSUE TITLE
How Can I make from 2d Canvas using image to 3d like this ?

### ISSUE THREAD

**Issue by benyaminl** [kevinroast/phoria.js#31]
How can i make 2d canvas image and put it on this image, the tiles..
![coloriser 2](https://cloud.githubusercontent.com/assets/2817332/15984736/9fd1ae64-2fff-11e6-9ccd-8fd37caf039f.png)

![simulation3_ref 10631](https://cloud.githubusercontent.com/assets/2817332/15984733/84e41f92-2fff-11e6-91b2-85540ce8d6fe.jpg)

**Comment by kevinroast** [comment]
You would need to model the scene in a 3D package, export it as various 3D object files in .obj format, import them into a Phoria scene and then add the tile as a texture image to a tesselated plan representing the floor object.
