### ISSUE TITLE
LOL

### ISSUE THREAD

**Issue by SamyBencherif** [kevinroast/phoria.js#41]
> What's all this then? - phoria.js is a JavaScript library for simple 3D graphics on a canvas 2D renderer. It **does not use WebGL** - so works on any device that can display HTML5 Canvas - so all modern browsers and including iOS and Android phones! **It uses the excellent vector and matrix maths library gl-matrix.js**.

gl-matrix uses WebGL, obviously.

**Comment by kevinroast** [comment]
I guess you can use this as a little life lesson on why you should do your research before making comments?

>gl-matrix uses WebGL, obviously.

Um no, sorry to burst your bubble. GL-matrix, if you read the documentation, is a _pure maths library_, it is not related to WebGL at all. The GL name part, comes from the original OpenGL spec - and the relationship to GL is that it performs the math matrix operations in the same row/column order as the original OpenGL specification.

"LOL"

**Comment by SamyBencherif** [comment]
Kevin roast you just kevin roasted me
