### ISSUE TITLE
Abandoned? :cry:

### ISSUE THREAD

**Issue by blokhin** [kevinroast/phoria.js#47]
Dear @kevinroast please, if possible, could you share your plans on **phoria.js**?

I have some code based on it and currently trying to understand how to proceed.

**Comment by kevinroast** [comment]
No plans i'm afraid, it's 10 years old this year :) it was a fun experiment and i enjoyed learning to write it and glad it was useful to some people! There are other libraries with much more support like THREE.js.

**Comment by wcdeich4** [comment]
There is also a project called "ts-phoria" that is based on Phoria.js but uses typescript.  But that project has also been abandoned.  I've been working on my own project that does not require WebGL, but it is still in its infancy.

**Comment by blokhin** [comment]
@wcdeich4 interestingly, the `three.js` [has dropped](https://twitter.com/mrdoob/status/1058022036038148096) the `CanvasRenderer` since `r98` in favor of WebGL.

**Comment by wcdeich4** [comment]
That is one of multiple reasons I hate three.js.
